teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 0
      y: 1
    scale_linear:
      x: 0.25
      y: 0.25
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.3
    enable_button: 5
    enable_turbo_button: 8
