azrael:
  controller_manager:
    ros__parameters:
      update_rate: 125  # Hz

      joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      imm_controller:
        type: imm_controller/ImmController

      cartesian_motion_controller:
        type: cartesian_motion_controller/CartesianMotionController

      force_torque_sensor_controller:
        type: force_torque_sensor_controller/ForceTorqueSensorController

      gripper_action_controller:
        type: position_controllers/GripperActionController
  
  joint_trajectory_controller:
    ros__parameters:
      joints:
        - azrael/shoulder_pan_joint
        - azrael/shoulder_lift_joint
        - azrael/elbow_joint
        - azrael/wrist_1_joint
        - azrael/wrist_2_joint
        - azrael/wrist_3_joint

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity

  # https://github.com/muttistefano/imm_controller.git
  imm_controller:
    ros__parameters:
      joints:
        - azrael/shoulder_pan_joint
        - azrael/shoulder_lift_joint
        - azrael/elbow_joint
        - azrael/wrist_1_joint
        - azrael/wrist_2_joint
        - azrael/wrist_3_joint
      command_joints:
        - azrael/shoulder_pan_joint
        - azrael/shoulder_lift_joint
        - azrael/elbow_joint
        - azrael/wrist_1_joint
        - azrael/wrist_2_joint
        - azrael/wrist_3_joint

      state_interface:
        - position
        - velocity
      control_interface:
        - position
      interface_name: position
      robot_chain_root: azrael/base_link
      robot_chain_tip: end_effector
      amr_base_link: azrael/base_footprint
      cmd_vel_topic: /azrael/cmd_vel
      only_robot: false
      omni: true

  # https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers
  cartesian_motion_controller:
    ros__parameters:
      end_effector_link: "azrael/tool0"
      robot_base_link: "azrael/base_link"
      joints:
        - azrael/shoulder_pan_joint
        - azrael/shoulder_lift_joint
        - azrael/elbow_joint
        - azrael/wrist_1_joint
        - azrael/wrist_2_joint
        - azrael/wrist_3_joint

      # See the cartesian_compliance_controller
      command_interfaces:
        - position
          #- velocity

      solver:
          error_scale: 1.0
          iterations: 10
          publish_state_feedback: True

      pd_gains:
          trans_x: {p: 2.0, i: 0.01}
          trans_y: {p: 2.0, i: 0.01}
          trans_z: {p: 2.0, i: 0.01}
          rot_x: {p: 0.5, i: 0.005}
          rot_y: {p: 0.5, i: 0.005}
          rot_z: {p: 0.5, i: 0.005}


  admittance_controller:
    ros__parameters:
      joints:
        - azrael/shoulder_pan_joint
        - azrael/shoulder_lift_joint
        - azrael/elbow_joint
        - azrael/wrist_1_joint
        - azrael/wrist_2_joint
        - azrael/wrist_3_joint

      command_interfaces:
        - position

      state_interfaces:
        - position
        - velocity
        - effort

      chainable_command_interfaces:
        - position
        - velocity

      kinematics:
        plugin_name: kinematics_interface_kdl/KinematicsInterfaceKDL
        plugin_package: kinematics_interface
        base: azrael/base_link # Assumed to be stationary
        tip: azrael/tool0
        group_name: arm
        alpha: 0.0005

      ft_sensor:
        name: azrael/robotiq_ft_sensor
        frame:
          id: azrael/robotiq_ft_frame_id
          external: false
        filter_coefficient: 0.005

      control:
        frame:
          id: azrael/tool0
          external: false

      fixed_world_frame:
        frame:
          id: map
          external: true

      gravity_compensation:
        frame:
          id: azrael/tool0
          external: false

        CoG: # TODO: To change
          pos: [0.0, 0.0, 0.1]
          force: 4.316

      admittance:
        selected_axes:
          - true # x
          - true # y
          - false # z
          - false # rx
          - false # ry
          - false # rz

        # Having ".0" at the end is MUST, otherwise there is a loading error
        # F = M*a + D*v + S*(x - x_d)
        mass:
          - 1.0
          - 1.0
          - 1.0
          - 1.0
          - 1.0
          - 1.0

        damping_ratio: # damping can be used instead: zeta = D / (2 * sqrt( M * S ))
          - 2.828427 # x
          - 2.828427 # y
          - 2.828427 # z
          - 2.828427 # rx
          - 2.828427 # ry
          - 2.828427 # rz

        stiffness:
          - 114.1
          - 114.2
          - 114.3
          - 114.4
          - 114.5
          - 114.6

          # - 214.1
          # - 214.2
          # - 214.3
          # - 214.4
          # - 214.5
          # - 214.6

  gripper_action_controller:
    ros__parameters:
      allow_stalling: true
      goal_tolerance: 0.01
      joint: finger_joint
      max_effort: 0.0
      stall_timeout: 1.5
      stall_velocity_threshold: 0.001
  