# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manipulator_controller:
  ros__parameters:
    joints:
      - azrael/shoulder_pan_joint
      - azrael/shoulder_lift_joint
      - azrael/elbow_joint
      - azrael/wrist_1_joint
      - azrael/wrist_2_joint
      - azrael/wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity