name: jazzy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-jazzy-desktop-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: azrael_app azrael_description azrael_driver_udp azrael_moveit_config
          target-ros2-distro: jazzy
          vcs-repo-file-url: dependencies.repos
          skip-tests: true
          colcon-defaults: |
            {
              "build": {
                "symlink-install": true
              },
              "test": {
                "parallel-workers": 1
              }
            }
